// Default tasks and subtasks for each construction stage
// References: IS codes (BIS), NBC 2016, CPWD specifications, SP 34/62, DSR rates
// Keys match the default stage names created in projects.js

const DEFAULT_STAGE_TASKS = {
  'Planning & Design': [
    // 1. Preliminary Feasibility & Site Assessment
    {
      title: 'Preliminary feasibility study and site assessment',
      priority: 'high',
      subtasks: [
        'Verify land ownership documents and title deed clearance',
        'Collect property survey number, village map and revenue records',
        'Assess site access roads, approach width and connectivity',
        'Study local development control regulations (DCR) and zoning',
        'Determine permissible FAR/FSI, ground coverage and height limits',
        'Identify applicable building bye-laws and setback requirements',
        'Assess availability of municipal water supply and sewage connection',
        'Check electrical power availability and nearest transformer capacity',
        'Evaluate neighborhood context — adjoining structures, party walls',
        'Prepare preliminary feasibility report with risk assessment',
      ],
    },
    // 2. Topographic Survey & Site Mapping
    {
      title: 'Topographic survey and site mapping',
      priority: 'high',
      subtasks: [
        'Engage licensed surveyor for total station / GPS survey',
        'Conduct topographical survey with contour mapping at 0.5m intervals (IS 1892)',
        'Mark plot boundaries with permanent boundary stones and GPS coordinates',
        'Record existing trees, utility lines, manholes and overhead cables',
        'Identify site bench mark (BM) and establish temporary bench marks (TBM)',
        'Measure and document road levels at plot entry points',
        'Note natural drainage patterns, slope direction and water flow',
        'Record distance to nearest municipal drain and sewer manhole',
        'Prepare site plan with north direction, dimensions and spot levels',
        'Submit survey report with coordinates, RL values and site photographs',
      ],
    },
    // 3. Geotechnical Investigation
    {
      title: 'Geotechnical investigation and soil testing',
      priority: 'high',
      subtasks: [
        'Engage geotechnical consultant and plan borehole locations',
        'Conduct soil boring at minimum 2 locations per 200 sqm (IS 1892:1979)',
        'Perform Standard Penetration Test (SPT) at every 1.5m depth (IS 2131:1981)',
        'Collect undisturbed soil samples for laboratory testing',
        'Conduct grain size analysis and soil classification (IS 1498:1970)',
        'Determine Atterberg limits — liquid limit, plastic limit, plasticity index',
        'Test natural moisture content and bulk density (IS 2720)',
        'Perform direct shear test or triaxial test for shear strength parameters',
        'Record groundwater table level and seasonal variation',
        'Conduct chemical analysis for sulphates, chlorides and pH (IS 2720-Part 26)',
        'Determine safe bearing capacity (SBC) with factor of safety >= 2.5 (IS 6403:1981)',
        'Prepare geotechnical investigation report with foundation recommendations',
      ],
    },
    // 4. Architectural Planning & Concept Design
    {
      title: 'Architectural planning and concept design',
      priority: 'high',
      subtasks: [
        'Gather detailed client brief — room requirements, lifestyle needs, budget range',
        'Study vastu/orientation preferences and sun path analysis',
        'Prepare 2-3 concept layout options with bubble diagrams',
        'Design floor plans with room sizes per NBC 2016 (habitable >= 9.5 sqm, kitchen >= 5 sqm)',
        'Ensure minimum ceiling height 2.75m habitable, 2.4m non-habitable (NBC Cl. 8.4)',
        'Design ventilation openings >= 1/6th of floor area per room (NBC Cl. 8.5)',
        'Plan staircase — width >= 1.0m, riser <= 190mm, tread >= 250mm (NBC Cl. 8.7)',
        'Design parking provisions as per local authority norms',
        'Include barrier-free accessibility features where required (NBC Cl. 11)',
        'Prepare site plan showing building footprint, setbacks and open spaces',
        'Present concept options to client and finalize preferred scheme',
      ],
    },
    // 5. Detailed Architectural Drawings
    {
      title: 'Detailed architectural drawing preparation',
      priority: 'high',
      subtasks: [
        'Prepare detailed floor plans for all levels with dimensions and annotations',
        'Draw cross-sections (minimum 2) showing floor heights, slab levels and foundation',
        'Prepare all four elevation drawings with material finishes indicated',
        'Design roof plan with slope direction, drainage outlets and parapet details',
        'Prepare door and window schedule with sizes, types and materials',
        'Draw detailed kitchen layout with platform, sink and appliance positions',
        'Design bathroom layouts with fixture positions and drainage slopes',
        'Prepare terrace and balcony details with railing height >= 1.05m (NBC)',
        'Draw staircase detail with dimensions, landing sizes and railing details',
        'Prepare site plan with landscaping, driveway and compound wall layout',
        'Include area statement — carpet area, built-up area, super built-up area, FAR calculation',
        'Prepare 3D visualization / walkthrough for client review',
      ],
    },
    // 6. Structural Engineering Design
    {
      title: 'Structural engineering design and analysis',
      priority: 'high',
      subtasks: [
        'Determine structural system — RCC frame, load-bearing, composite',
        'Define design parameters — concrete grade (M20/M25), steel grade (Fe 500D)',
        'Calculate dead loads (DL) — self-weight of slab, beam, wall, finishes per IS 875-Part 1',
        'Calculate live loads (LL) — residential 2.0 kN/sqm, terrace 1.5 kN/sqm per IS 875-Part 2',
        'Perform wind load analysis based on basic wind speed and terrain (IS 875:2015 Part 3)',
        'Perform seismic analysis per IS 1893:2016 — determine zone factor, importance factor, response reduction',
        'Run structural analysis using ETABS/STAAD for all load combinations (1.5DL+1.5LL, 1.2DL+1.2LL+1.2EQ etc.)',
        'Design isolated/combined footings based on SBC and load calculations (IS 456)',
        'Design plinth beams with minimum reinforcement per IS 456 Cl. 26.5',
        'Design columns for axial load + bending — check slenderness, steel 0.8-4% (IS 456 Cl. 26.5.3)',
        'Design beams for flexure and shear — check deflection limit span/250 (IS 456 Cl. 23.2)',
        'Design slabs for bending, shear and deflection — min thickness 120mm',
        'Design staircase — waist slab, landing and mid-landing reinforcement',
        'Apply ductile detailing per IS 13920:2016 for beam-column junctions',
        'Check punching shear for flat slabs / footings if applicable',
        'Prepare structural design report with design assumptions, calculations and conclusions',
      ],
    },
    // 7. Structural Drawings & Detailing
    {
      title: 'Structural drawing preparation and detailing',
      priority: 'high',
      subtasks: [
        'Prepare foundation layout plan with footing sizes, pedestal locations',
        'Draw footing reinforcement details — bottom mat, top mat, cover 50mm (IS 456 Table 16)',
        'Prepare column schedule — section sizes, main bars, ties spacing for each floor',
        'Draw beam schedule — section sizes, top/bottom reinforcement, stirrup spacing',
        'Prepare slab reinforcement layout — main bars, distribution bars, extra bars at supports',
        'Draw staircase reinforcement detail with waist slab and landing bars',
        'Prepare lintel and chajja (sunshade) reinforcement details',
        'Draw plinth beam reinforcement details',
        'Prepare bar bending schedule (BBS) with cutting lengths per SP 34:1987',
        'Calculate total steel quantity from BBS — grade-wise (8mm, 10mm, 12mm, 16mm, 20mm)',
        'Draw construction joint locations and treatment details',
        'Include standard notes — cover, lap lengths (45d compression, 50d tension), hook details',
      ],
    },
    // 8. Electrical System Design
    {
      title: 'Electrical system design and drawing',
      priority: 'high',
      subtasks: [
        'Calculate total connected electrical load for the building (IS 732:1989)',
        'Design lighting layout — points per room based on lux level requirements (IS 3646)',
        'Design power socket layout — 5A for lighting, 15A for heavy appliances',
        'Plan AC provision points with dedicated circuits and MCBs',
        'Design distribution board (DB) layout — MCB sizing and circuit allocation',
        'Select main switch/RCCB rating and incoming cable size',
        'Design earthing system — plate/pipe earthing with resistance < 5 ohms (IS 3043:2018)',
        'Plan lightning protection if building height > 15m (IS 2309)',
        'Design conduit routing plan — concealed PVC conduits in slab and walls',
        'Plan external electrical — meter room, EB connection, DG set provision if needed',
        'Design intercom, CCTV, internet conduit provisions',
        'Prepare electrical load chart, single line diagram and wiring schedule',
      ],
    },
    // 9. Plumbing & Sanitary System Design
    {
      title: 'Plumbing and sanitary system design',
      priority: 'high',
      subtasks: [
        'Calculate water demand at 135 LPCD and design overhead/underground tank capacity (IS 1172:1993)',
        'Design cold water distribution — pipe sizing, GI/CPVC routing from tank to fixtures',
        'Design hot water system — geyser locations, CPVC hot water piping',
        'Plan water supply riser and branch connections with valves at each floor',
        'Design soil and waste pipe layout — 100mm soil, 75mm waste (IS 1742:1983)',
        'Design vent pipe system to prevent trap seal loss',
        'Plan floor drain locations in bathrooms with minimum 1:40 slope towards drain',
        'Design rainwater downpipe layout from terrace to ground drain',
        'Design septic tank and soak pit if municipal sewer unavailable (IS 2470)',
        'Design rainwater harvesting system — rooftop collection, filter, recharge well (NBC Part 9)',
        'Plan water meter location, main valve and isolation valve positions',
        'Prepare plumbing isometric drawings and fixture schedule',
      ],
    },
    // 10. HVAC & Fire Safety Design
    {
      title: 'HVAC and fire safety provisions',
      priority: 'medium',
      subtasks: [
        'Calculate cooling load per room and recommend AC tonnage',
        'Plan AC outdoor unit locations with adequate ventilation',
        'Design AC drain piping to designated collection point',
        'Plan cross-ventilation strategy for naturally ventilated spaces',
        'Design fire exit routes and emergency signage (NBC Part 4)',
        'Specify fire extinguisher types, locations and quantity',
        'Plan fire-resistant construction per NBC — door rating, material selection',
        'Design smoke detector and fire alarm layout if building > 15m height',
      ],
    },
    // 11. Cost Estimation & BOQ Preparation
    {
      title: 'Detailed cost estimation and BOQ preparation',
      priority: 'high',
      subtasks: [
        'Compute earthwork quantities — excavation, backfilling, sand filling (IS 1200-Part 1)',
        'Calculate concrete quantities grade-wise — PCC, M20, M25 (IS 1200-Part 2)',
        'Calculate steel reinforcement quantity from BBS — total weight grade-wise',
        'Compute brickwork quantities — 230mm external, 115mm internal walls (IS 1200-Part 6)',
        'Calculate plastering quantities — internal 12mm, external 20mm (IS 1200-Part 12)',
        'Compute flooring and tiling quantities — room-wise with wastage 5-10%',
        'Calculate painting quantities — primer, putty, emulsion, exterior (IS 1200-Part 13)',
        'Compute plumbing material quantities — pipes, fittings, fixtures',
        'Calculate electrical material quantities — cables, conduits, switches, DBs',
        'Prepare detailed rate analysis using current DSR/SSR rates (CPWD/State PWD)',
        'Compile abstract of cost — stage-wise summary with material and labour breakup',
        'Add contingency provision 3-5% and escalation clause (CPWD Manual)',
        'Prepare final bill of quantities (BOQ) document with item-wise rates and amounts',
        'Present cost estimate to client — get budget approval and payment schedule',
      ],
    },
    // 12. Construction Planning & Scheduling
    {
      title: 'Construction planning and project scheduling',
      priority: 'medium',
      subtasks: [
        'Prepare work breakdown structure (WBS) for all construction stages',
        'Define activity sequence and dependencies — predecessor/successor relationships',
        'Estimate duration for each activity based on labour output and resource availability',
        'Prepare CPM/PERT network diagram (SP 62:1997 Chapter 1)',
        'Create project schedule — Gantt chart with milestones and critical path',
        'Plan resource leveling — labour, equipment, material delivery schedules',
        'Identify long-lead procurement items — steel, cement, sanitary fixtures, doors/windows',
        'Plan construction methodology — sequence of operations, access routes, crane locations',
        'Define quality control checkpoints at each stage',
        'Establish project communication plan — reporting frequency, stakeholder meetings',
      ],
    },
    // 13. Quality Assurance & Safety Planning
    {
      title: 'Quality assurance and site safety planning',
      priority: 'medium',
      subtasks: [
        'Prepare quality assurance plan (QAP) — inspection and test procedures per stage',
        'Define material testing requirements — cement, steel, aggregate, brick, concrete cubes',
        'Establish concrete mix design protocol — trial mix, cube testing at 7 and 28 days',
        'Plan site laboratory or identify nearby NABL-accredited testing lab',
        'Prepare site safety plan — PPE requirements, fall protection, scaffolding safety',
        'Define emergency procedures — first aid, fire, evacuation routes',
        'Plan barricading, safety signage and visitor safety protocols (IS 3764:1992)',
        'Prepare construction waste management and disposal plan',
      ],
    },
    // 14. Drawing Coordination & Design Review
    {
      title: 'Drawing coordination and interdisciplinary design review',
      priority: 'high',
      subtasks: [
        'Conduct clash detection between architectural, structural and MEP drawings',
        'Verify beam locations do not conflict with door/window openings',
        'Check column positions align between architectural and structural plans',
        'Verify plumbing risers and drainage routes do not conflict with structural members',
        'Confirm electrical conduit routing avoids structural reinforcement congestion',
        'Ensure AC outdoor unit locations have structural provision (slab cutouts/brackets)',
        'Cross-verify all drawings use consistent floor levels, grid lines and dimensions',
        'Compile final coordinated drawing set — architecture, structure, electrical, plumbing',
        'Conduct design review meeting with all consultants — architect, structural, MEP',
        'Obtain client sign-off on final coordinated drawing set before construction',
      ],
    },
    // 15. Tender & Contractor Selection
    {
      title: 'Tender preparation and contractor selection',
      priority: 'medium',
      subtasks: [
        'Prepare tender documents — BOQ, drawings, specifications, terms and conditions',
        'Define scope of work clearly — inclusions, exclusions, owner-supplied items',
        'Invite quotations from minimum 3 qualified contractors',
        'Conduct comparative analysis of received quotations',
        'Verify contractor credentials — experience, past projects, financial capacity',
        'Negotiate rates and finalize contract value',
        'Prepare construction agreement — payment terms, milestones, penalties, defect liability',
        'Issue work order / letter of intent to selected contractor',
      ],
    },
  ],

  'Approvals & Permits': [
    // 1. Building Plan Submission & Approval
    {
      title: 'Building plan submission and approval from local authority',
      priority: 'high',
      subtasks: [
        'Prepare building plan application with prescribed forms and fees',
        'Submit site plan showing plot boundaries, setbacks, access road width',
        'Submit floor plans, cross-sections and elevations as per sanctioned layout',
        'Submit FAR/FSI calculation and ground coverage statement within permissible limits',
        'Submit height restriction compliance certificate as per local bye-laws',
        'Provide property ownership proof — title deed, encumbrance certificate, tax receipts',
        'Submit NOC from registered society/layout authority if applicable',
        'Address revision comments from plan scrutiny and resubmit if required',
        'Obtain building plan approval / sanctioned plan from local authority',
        'Collect certified sanctioned plan copies for site and record',
      ],
    },
    // 2. Structural Stability Certificate
    {
      title: 'Structural stability certificate and engineering approvals',
      priority: 'high',
      subtasks: [
        'Obtain structural stability certificate from licensed structural engineer',
        'Submit structural design calculations to local authority',
        'Submit structural drawings reviewed and stamped by licensed engineer',
        'Attach soil investigation report with foundation design recommendation',
        'Submit seismic compliance certificate per IS 1893:2016 for applicable zone',
        'Obtain structural engineering approval from local body',
      ],
    },
    // 3. Environmental & Utility Clearances
    {
      title: 'Environmental clearances and utility connection approvals',
      priority: 'high',
      subtasks: [
        'Apply for water supply connection from municipal water board',
        'Apply for sewerage connection from local municipality',
        'Apply for temporary and permanent electrical supply connection',
        'Obtain tree cutting / transplanting permission if applicable',
        'Obtain NOC from airport authority if site is in restricted height zone',
        'Obtain NOC from fire department for buildings per NBC Part 4 requirements',
        'Obtain pollution control board clearance if applicable (CTE/CTO)',
        'Apply for rainwater harvesting compliance certificate (mandatory in many states)',
        'Obtain NOC from traffic authority if site fronts a major road',
      ],
    },
    // 4. Commencement Certificate
    {
      title: 'Construction commencement certificate and site permits',
      priority: 'high',
      subtasks: [
        'Apply for and obtain construction commencement certificate from local authority',
        'Complete boundary demarcation and verification by local surveyor',
        'Erect mandatory display board at site — license number, architect, contractor details',
        'Maintain copy of approved/sanctioned plan at site at all times',
        'Register with labour department under Building and Other Construction Workers Act',
        'Obtain necessary road cutting / excavation permission from PWD if applicable',
        'Arrange for temporary water and electricity connections for construction',
      ],
    },
    // 5. Insurance & Legal Documentation
    {
      title: 'Insurance, legal documentation and contractor registration',
      priority: 'medium',
      subtasks: [
        'Arrange contractor all-risk (CAR) insurance policy',
        'Arrange workmen compensation insurance for labourers',
        'Prepare and execute construction agreement with contractor',
        'Register project under RERA if applicable (Real Estate Regulation Act)',
        'Arrange third-party liability insurance',
        'Set up site safety documentation register as per IS 3764:1992',
        'Prepare environmental management plan for dust, noise and waste control',
      ],
    },
  ],

  'Foundation': [
    // 1. Site Preparation & Layout
    {
      title: 'Site preparation, clearing and layout marking',
      priority: 'high',
      subtasks: [
        'Clear site of vegetation, debris and organic matter to minimum 150mm depth (IS 3764:1992)',
        'Set up temporary fencing, security gate and site office',
        'Arrange temporary water supply, electrical connection and storage shed',
        'Set up material storage area — cement godown, steel yard, aggregate stockpile',
        'Mark building grid lines and centerlines using theodolite / total station',
        'Establish permanent site bench mark (BM) and reference pillars',
        'Transfer building layout from drawing to ground with lime marking',
        'Cross-verify all dimensions, diagonals and setbacks before excavation',
        'Install profile boards / batter boards at corners for excavation reference',
        'Photograph site condition before excavation (baseline documentation)',
      ],
    },
    // 2. Excavation
    {
      title: 'Foundation excavation and soil verification',
      priority: 'high',
      subtasks: [
        'Excavate to foundation depth as per structural drawing +/- 50mm tolerance (IS 3764:1992)',
        'Maintain excavation sides properly sloped or shored for depth > 1.5m (IS 3764 Cl. 5)',
        'Stack excavated soil minimum 1m away from excavation edge (IS 3764)',
        'Verify excavation bottom reaches designed founding level — check with benchmark',
        'Compact bottom of excavation to minimum 95% MDD (IS 2720-Part 7)',
        'Arrange dewatering pumps if groundwater is encountered (IS 9759:1981)',
        'Record soil strata encountered and compare with soil investigation report',
        'Get engineer approval on founding level before proceeding to PCC',
        'Conduct plate load test if SBC needs field verification (IS 1888:1982)',
        'Photograph and document excavation with measurements',
      ],
    },
    // 3. PCC Bed
    {
      title: 'Plain cement concrete (PCC) bed for footings',
      priority: 'high',
      subtasks: [
        'Verify PCC mix grade — M10 (1:3:6) or M15 (1:2:4) as per specification (IS 456 Cl. 9)',
        'Lay PCC minimum 100mm thick over entire footing area and 150mm beyond footing edge',
        'Ensure PCC surface is level and compacted — check with spirit level',
        'Mark footing centerlines on PCC surface after setting',
        'Cure PCC for minimum 2 days before placing reinforcement',
        'Get engineer approval on PCC level and surface before rebar placement',
      ],
    },
    // 4. Footing Construction
    {
      title: 'Footing reinforcement and concrete casting',
      priority: 'high',
      subtasks: [
        'Cut and bend footing reinforcement as per bar bending schedule (SP 34:1987)',
        'Place footing bottom mat reinforcement with correct cover 50mm using cover blocks (IS 456 Table 16)',
        'Verify rebar diameter, spacing and lap lengths as per structural drawing',
        'Place column starter bars / dowels at correct position and plumb (IS 13920)',
        'Fix footing formwork — ensure correct dimensions within +/- 10mm tolerance',
        'Get engineer/inspector approval on reinforcement before pouring concrete',
        'Cast footings with minimum M20 grade concrete (IS 456 Cl. 6.1)',
        'Vibrate concrete thoroughly — no honeycombing or segregation (IS 456 Cl. 13.3)',
        'Collect concrete cube samples — minimum 3 cubes per 15 cum (IS 456 Cl. 15.2)',
        'Cure footings by ponding for minimum 7 days (IS 456 Cl. 13.5)',
        'Record footing dimensions and concrete pour details in site register',
      ],
    },
    // 5. Plinth Beam Construction
    {
      title: 'Plinth beam construction and curing',
      priority: 'high',
      subtasks: [
        'Construct plinth beam formwork — aligned, level and properly supported (IS 14687:1999)',
        'Place plinth beam reinforcement — min 2 bars of 12mm at top and bottom (IS 456 Cl. 26.5)',
        'Fix stirrups at maximum spacing 300mm c/c or d/2 whichever is less (IS 456 Cl. 26.5.1.6)',
        'Verify reinforcement cover 25-40mm with cover blocks at max 1m spacing',
        'Get pre-pour inspection approval from engineer/inspector',
        'Cast plinth beam with M20 concrete without segregation — vibrate properly',
        'Treat construction joints with bonding agent if casting is done in stages (IS 456 Cl. 13.4)',
        'Verify plinth level matches benchmark level as per drawing',
        'Collect concrete cube test specimens during pouring',
        'Cure plinth beam for minimum 7 days by wet hessian or ponding',
      ],
    },
    // 6. DPC (Damp Proof Course)
    {
      title: 'Damp proof course (DPC) application',
      priority: 'high',
      subtasks: [
        'Verify DPC level is minimum 150mm above finished ground level (IS 2645:2003)',
        'Clean and wet surface below DPC layer thoroughly',
        'Apply DPC material — CM 1:1.5:3 with waterproofing compound, minimum 50mm thick (IS 2645)',
        'Ensure DPC is continuous across all walls without breaks',
        'Apply bitumen-based DPC coat on both sides of basement walls if below ground (IS 2645)',
        'Allow DPC to cure for 48 hours before starting brickwork above',
      ],
    },
    // 7. Anti-Termite Treatment
    {
      title: 'Anti-termite treatment of soil and foundation',
      priority: 'high',
      subtasks: [
        'Engage licensed pest control agency with approved termiticide (IS 6313:2013 Part 2)',
        'Apply soil treatment at 5 litres per sqm concentration at plinth level (IS 6313)',
        'Treat soil on both sides of foundation walls and around all footings',
        'Apply chemical barrier at junction of floor and wall',
        'Treat refilled earth in plumbing trenches and utility entry points',
        'Obtain anti-termite treatment certificate with warranty period (min 10 years)',
        'Record treatment details — chemical used, concentration, date, area covered',
      ],
    },
    // 8. Backfilling & Compaction
    {
      title: 'Backfilling, compaction and sand filling',
      priority: 'high',
      subtasks: [
        'Ensure backfill material is free from organic matter, debris and stones > 75mm (IS 2720-Part 4)',
        'Do not backfill against green concrete — wait minimum 7 days after casting (IS 456)',
        'Backfill in layers of maximum 200-300mm thickness (IS 2720-Part 7)',
        'Compact each layer to minimum 95% maximum dry density (MDD) (IS 2720-Part 8)',
        'Maintain optimum moisture content during compaction (IS 2720-Part 7)',
        'Place clean sand filling below ground floor slab — minimum 150mm compacted thickness',
        'Conduct field density test (core cutter/sand replacement) to verify compaction (IS 2720-Part 28/29)',
        'Ensure finished ground level matches drawing specifications',
      ],
    },
    // 9. Foundation Quality & Testing
    {
      title: 'Foundation quality control and testing',
      priority: 'high',
      subtasks: [
        'Test cement — initial setting time min 30 min, final max 600 min (IS 4031)',
        'Test reinforcement steel — tensile strength, elongation per IS 1786 (Fe 500D)',
        'Test concrete cube strength at 7 days (min 67% of 28-day strength) (IS 516)',
        'Test concrete cube strength at 28 days — verify characteristic strength achieved (IS 456 Cl. 15)',
        'Conduct slump test for every batch — 75-100mm for RCC work (IS 1199)',
        'Test coarse aggregate — grading, flakiness index, impact value (IS 383:2016)',
        'Test fine aggregate — grading zone, silt content max 3% (IS 383)',
        'Maintain concrete register — date, mix, slump, location, cube ID for each pour',
        'Get structural engineer sign-off on foundation completion before backfilling',
      ],
    },
  ],

  'Structure': [
    // 1. Column Construction
    {
      title: 'Column reinforcement, formwork and casting',
      priority: 'high',
      subtasks: [
        'Cut and bend column reinforcement as per BBS and structural drawing (SP 34:1987)',
        'Verify column main bar diameter and number — min 4 bars for rectangular, 6 for circular (IS 456 Cl. 26.5.3)',
        'Verify longitudinal steel percentage is between 0.8% and 4% of cross-section (IS 456 Cl. 26.5.3.1)',
        'Fix lateral ties — minimum 8mm dia, spacing <= 300mm or least lateral dimension (IS 456 Cl. 26.5.3.2)',
        'Provide special confining reinforcement at beam-column joints per IS 13920:2016',
        'Verify lap length — minimum 45d for compression, 50d for tension (IS 456 Cl. 26.2.5)',
        'Ensure clear cover 40mm with cover blocks placed at max 1m interval (IS 456 Table 16)',
        'Erect column formwork — check plumb within +/- 5mm per 3m height (IS 14687:1999)',
        'Get pre-pour approval from engineer on reinforcement and formwork',
        'Cast columns with M20/M25 concrete, slump 75-100mm — vibrate thoroughly (IS 456)',
        'Collect concrete cube test specimens — min 3 per batch (IS 516:1959)',
        'Cure columns for minimum 7 days — wet gunny or curing compound',
        'Strip column formwork after minimum 24 hours for vertical members (IS 456 Table 11)',
        'Inspect columns for honeycombing — apply grouting/repair if defects found',
      ],
    },
    // 2. Beam Reinforcement & Formwork
    {
      title: 'Beam reinforcement, formwork and casting',
      priority: 'high',
      subtasks: [
        'Install beam bottom shuttering with props at minimum 1.2m spacing (IS 14687:1999)',
        'Verify beam dimensions as per drawing — tolerance +/- 5mm (IS 456)',
        'Place beam bottom reinforcement as per BBS — verify bar diameter and number (IS 456 Cl. 26.5.1)',
        'Verify minimum tension steel: 0.85bd/fy (IS 456 Cl. 26.5.1.1)',
        'Place shear stirrups at max spacing d/2 or 300mm whichever is less (IS 456 Cl. 26.5.1.6)',
        'Provide extra closed stirrups at beam-column junction zone per IS 13920 Cl. 6.3',
        'Place side face reinforcement if beam depth exceeds 750mm (IS 456 Cl. 26.5.1.3)',
        'Ensure clear cover 25mm for beams with cover blocks (IS 456 Table 16)',
        'Fix beam side formwork — aligned, level and braced (IS 14687)',
        'Verify top reinforcement is placed after slab bottom bars at beam-slab junction',
        'Get pre-pour inspection and approval from structural engineer',
      ],
    },
    // 3. Slab Reinforcement & Casting
    {
      title: 'Slab reinforcement, formwork and concrete casting',
      priority: 'high',
      subtasks: [
        'Install slab formwork / shuttering on props — check level +/- 3mm (IS 14687:1999)',
        'Verify slab thickness as per drawing — minimum 120mm for residential (IS 456)',
        'Place main reinforcement bars as per drawing — minimum 8mm bars (IS 456 Cl. 26.5.2)',
        'Place distribution steel — minimum 0.12% of gross area for HYSD bars (IS 456 Cl. 26.5.2.1)',
        'Verify maximum bar spacing — min(3d, 300mm) for main, min(5d, 450mm) for distribution (IS 456 Cl. 26.3.3)',
        'Place extra top bars at supports and crank bars per drawing',
        'Ensure electrical and plumbing sleeves/pipes are placed before concreting (IS 732)',
        'Ensure clear cover 15-20mm for slab with cover blocks (IS 456 Table 16)',
        'Check chair bars to maintain top mat at correct level in two-way slabs',
        'Get pre-pour approval from engineer on reinforcement and embedded items',
        'Cast slab in one continuous pour — no cold joints (IS 456 Cl. 13.3)',
        'Vibrate concrete thoroughly and finish surface to level and slope as required',
        'Start ponding/curing within 24 hours — maintain wet curing for minimum 7 days (IS 456 Cl. 13.5)',
        'Collect concrete cube samples — min 3 per 15 cum or per pour (IS 456 Cl. 15.2)',
        'Do not remove slab formwork before 14 days for spans < 4.5m, 21 days for larger (IS 456 Table 11)',
      ],
    },
    // 4. Staircase Construction
    {
      title: 'Staircase construction and detailing',
      priority: 'medium',
      subtasks: [
        'Verify staircase dimensions — width >= 1000mm, riser <= 190mm, tread >= 250mm (NBC 2016 Cl. 8.7)',
        'Ensure riser and tread are uniform throughout — tolerance +/- 3mm (NBC)',
        'Prepare staircase waist slab formwork per structural drawing (IS 456)',
        'Place waist slab reinforcement — main bars and distribution steel as per drawing',
        'Ensure landing reinforcement is properly lapped with waist slab bars',
        'Cast staircase in sequence — flight first, then landing — avoid cold joints',
        'Verify landing size minimum 1.0m x width at every floor (NBC 2016)',
        'Maximum 12 risers per flight without intermediate landing (NBC 2016)',
        'Cure staircase for minimum 7 days before stripping formwork',
        'Check finished riser and tread dimensions after stripping',
      ],
    },
    // 5. Lintel & Chajja (Sunshade) Casting
    {
      title: 'Lintel, chajja and miscellaneous RCC member casting',
      priority: 'medium',
      subtasks: [
        'Cast lintels above every door and window opening with min 150mm bearing on each side (IS 456)',
        'Verify lintel depth minimum 100mm or as per design for span (IS 456)',
        'Provide minimum 2 bars of 10mm at top and bottom with 6mm stirrups (IS 456)',
        'Cast chajja (sunshade) reinforcement as per cantilever design',
        'Ensure chajja slope for water drainage — minimum 1:100 outward (NBC 2016)',
        'Provide drip groove / drip mould at chajja outer edge to prevent water seepage',
        'Cast parapet starter reinforcement if not done with roof slab',
        'Cast any RCC shelves, loft slabs or projections per architectural drawing',
        'Cure all cast members for minimum 7 days',
      ],
    },
    // 6. Concrete Mix Design & Quality Control
    {
      title: 'Concrete mix design, testing and quality control',
      priority: 'high',
      subtasks: [
        'Prepare concrete mix design for M20/M25 per IS 10262:2019 with trial mixes',
        'Conduct slump test for every batch — maintain 75-100mm for RCC (IS 1199:1959)',
        'Collect concrete cube specimens — min 3 cubes per 15 cum or per pour day (IS 456 Cl. 15.2)',
        'Test 7-day compressive strength — should achieve min 67% of design strength (IS 516)',
        'Test 28-day compressive strength — verify characteristic strength fck achieved (IS 516)',
        'Maintain concrete register — date, grade, location, volume, slump, cube IDs',
        'Test rebound hammer readings on hardened concrete for uniformity (IS 13311-Part 2)',
        'Arrange non-destructive testing (UPV) if core strength results are suspect (IS 13311-Part 1)',
        'Verify water-cement ratio not exceeding 0.50 for M20 and 0.45 for M25 (IS 456 Table 5)',
        'Ensure concrete temperature at placement does not exceed 30°C in hot weather (IS 7861)',
      ],
    },
    // 7. Formwork Management
    {
      title: 'Formwork inspection, removal schedule and reuse',
      priority: 'medium',
      subtasks: [
        'Inspect all formwork before concrete pour — alignment, support, tightness (IS 14687:1999)',
        'Apply mould release agent on formwork surfaces before rebar placement',
        'Verify prop spacing and bracing adequacy for slab and beam loads',
        'Follow minimum stripping time — columns 24h, beam sides 3 days, slab soffit 14 days (IS 456 Table 11)',
        'Re-prop slabs after early stripping if required (spans > 4.5m keep 21 days)',
        'Inspect formwork for damage before reuse — discard warped or broken panels',
        'Maintain formwork stripping log — date cast, date stripped, curing status',
      ],
    },
  ],

  'Brickwork': [
    // 1. Material Testing & Procurement
    {
      title: 'Brick and mortar material testing and procurement',
      priority: 'high',
      subtasks: [
        'Procure bricks with minimum compressive strength 3.5 N/mm2 — Class A or above (IS 1077:1992)',
        'Test bricks — compressive strength, water absorption < 20%, efflorescence nil/slight (IS 3495)',
        'Check brick dimensions — standard 230x110x75mm, tolerance +/- 3mm (IS 1077)',
        'Conduct brick field tests — drop test, ring test, visual inspection for cracks',
        'Test mortar — compressive strength per mix design (IS 2250:1981)',
        'Verify cement quality — consistency, setting time, soundness (IS 4031)',
        'Test sand — silt content max 3%, grading per Zone II/III (IS 383:2016)',
        'Prepare mortar mix — CM 1:6 for superstructure, CM 1:4 for load-bearing (IS 2250)',
        'Get engineer approval on brick sample and mortar mix ratio before starting brickwork',
      ],
    },
    // 2. External Wall Construction (230mm)
    {
      title: 'External wall construction in 230mm brickwork',
      priority: 'high',
      subtasks: [
        'Soak bricks in water for minimum 2 hours before laying (IS 2212:1991)',
        'Lay bricks in English bond pattern for 230mm walls per IS 2212',
        'Maintain bed joint thickness 10mm +/- 3mm uniform throughout (IS 2212)',
        'Maintain perpend (vertical) joints at 10mm — properly staggered',
        'Check wall plumbness at every 3 courses — tolerance +/- 5mm per 3m (IS 2212)',
        'Provide toothing / bonding at wall junctions with cross walls (IS 2212)',
        'Restrict maximum wall height to 1.5m per day to avoid settlement (IS 2212)',
        'Leave window and door openings per drawing with correct sill height',
        'Embed MS hold-fasts for door frames at required heights',
        'Fill gap between top of wall and beam soffit with mortar after 14 days drying (IS 2212)',
        'Cure brickwork for minimum 7 days by spraying water (IS 2212)',
      ],
    },
    // 3. Internal Partition Walls (115mm)
    {
      title: 'Internal partition wall construction in 115mm brickwork',
      priority: 'high',
      subtasks: [
        'Lay internal partition walls in stretcher bond — 115mm thick (IS 1905:1987)',
        'Bond partition walls to main walls with MS L-ties / wire mesh at every 3rd course (IS 1905)',
        'Provide expansion joints at junctions with RCC columns using flexible sealant',
        'Leave door openings per drawing with frame hold-fasts embedded',
        'Chase depth for concealed electrical/plumbing max 1/3 of wall thickness (IS 2212)',
        'Fill top course gap after minimum 14 days — prevent cracking from settlement',
        'Cure internal walls for minimum 7 days',
      ],
    },
    // 4. Parapet Wall Construction
    {
      title: 'Parapet wall construction on terrace',
      priority: 'high',
      subtasks: [
        'Construct parapet wall minimum 1.0m height above terrace FFL (NBC 2016 Cl. 8.8)',
        'Minimum parapet thickness 230mm as per NBC 2016',
        'Anchor parapet to roof slab with MS dowel bars at 600mm c/c (IS 4326:2013)',
        'Provide coping on top of parapet with outward slope for water drainage',
        'Provide weep holes at 2m c/c along parapet base for terrace water drainage',
        'Provide corner reinforcement with L-bars at parapet junctions',
        'Cure parapet wall for minimum 7 days',
      ],
    },
    // 5. RCC Band / Lintel Band (Seismic)
    {
      title: 'Seismic bands — lintel band and gable band per IS 4326',
      priority: 'high',
      subtasks: [
        'Cast continuous RCC lintel band at lintel level in all external and internal load-bearing walls (IS 4326:2013 Cl. 8.4)',
        'Provide minimum 2 bars of 10mm with 6mm stirrups at 150mm c/c for band (IS 4326)',
        'Ensure band is continuous at corners — provide L-shaped anchorage bars',
        'Cast gable band at top of gable wall for sloped roof buildings (IS 4326)',
        'Verify band dimensions — min 75mm x wall width as per IS 4326',
        'Cure bands for minimum 7 days before loading',
      ],
    },
    // 6. Masonry Quality Checks & Curing
    {
      title: 'Brickwork quality inspection, curing and documentation',
      priority: 'medium',
      subtasks: [
        'Check wall alignment and plumbness with spirit level at every 3 courses (IS 2212)',
        'Verify opening dimensions match drawing — door, window, ventilator sizes',
        'Check mortar joint quality — no voids, proper filling, uniform thickness',
        'Collect mortar cube samples — min 3 per floor for compressive testing (IS 2250)',
        'Inspect for through cracks, efflorescence or water seepage (IS 1905)',
        'Cure all brickwork for minimum 7 days from completion',
        'Document wall heights, openings and any deviations in site register',
        'Get engineer sign-off on brickwork completion before plastering',
      ],
    },
  ],

  'Roofing': [
    // 1. Roof Slab Construction
    {
      title: 'Roof slab reinforcement, formwork and casting',
      priority: 'high',
      subtasks: [
        'Install roof slab formwork with adequate propping and bracing (IS 14687:1999)',
        'Verify slab thickness as per structural drawing — minimum 120mm (IS 456)',
        'Place reinforcement with correct spacing, cover and chair bars (IS 456 Cl. 26.5.2)',
        'Form slope towards rainwater outlets — minimum 1:100 gradient (NBC 2016)',
        'Place opening reinforcement for staircase headroom, tank supports, plumbing risers',
        'Embed electrical conduits and plumbing sleeves before casting',
        'Get pre-pour approval on reinforcement and embedded services',
        'Cast roof slab in one continuous pour — vibrate thoroughly (IS 456 Cl. 13.3)',
        'Finish surface with required slope and cure by ponding minimum 14 days (IS 456 Cl. 13.5)',
        'Collect concrete cube samples per standard (IS 456 Cl. 15.2)',
        'Do not remove formwork for minimum 14 days for spans < 4.5m (IS 456 Table 11)',
      ],
    },
    // 2. Waterproofing Treatment
    {
      title: 'Roof waterproofing treatment and testing',
      priority: 'high',
      subtasks: [
        'Clean roof surface — remove laitance, dust, loose material (IS 3067:1988)',
        'Repair all cracks, honeycombs with polymer-modified cement mortar before treatment',
        'Apply primer / bonding coat as per waterproofing system specification',
        'Apply APP/SBS modified bituminous membrane or liquid waterproofing membrane (IS 3067)',
        'Lay brick bat coba — 80mm average thickness with CM 1:4 mortar (IS 3067)',
        'Apply IPS (Indian Patent Stone) finish — CM 1:2, 20mm thick with waterproofing (IS 3067)',
        'Turn up waterproofing on parapet walls minimum 300mm above FFL (IS 3067)',
        'Seal all pipe penetrations, vent openings and drain connections watertight',
        'Form groove joints in IPS at 3m x 3m grid to control shrinkage cracks',
        'Conduct water ponding test for minimum 72 hours — verify no leakage (IS 3067)',
        'Rectify any leakage points and re-test until no seepage observed',
        'Apply reflective / heat-resistant cool roof coating for thermal comfort',
      ],
    },
    // 3. Parapet Wall & Coping
    {
      title: 'Roof parapet wall, coping and railing',
      priority: 'high',
      subtasks: [
        'Construct parapet wall minimum 1.0m height with 230mm thickness (NBC 2016 Cl. 8.8)',
        'Anchor parapet with MS dowels at 600mm c/c into roof slab (IS 4326)',
        'Apply coping on parapet top with outward slope — prevent water ingress',
        'Provide weep holes at parapet base at 2m centres for drainage',
        'Install MS railing on parapet if required — minimum height 1.0m (NBC)',
        'Apply waterproofing on inner face of parapet up to 300mm above roof FFL',
      ],
    },
    // 4. Rainwater Drainage System
    {
      title: 'Roof rainwater drainage and outlet system',
      priority: 'high',
      subtasks: [
        'Install rainwater outlets / rain water pipes (RWP) at lowest points of roof slope',
        'Connect RWP to downpipes — 100mm diameter minimum for roof area served',
        'Ensure proper slope in roof towards outlets — minimum 1:100 (NBC)',
        'Install leaf guards / gratings at all roof outlets',
        'Connect downpipes to ground-level storm water drain or rainwater harvesting system',
        'Test drainage by flooding — verify water drains completely within 30 minutes',
      ],
    },
    // 5. Thermal Insulation & Roof Accessories
    {
      title: 'Roof thermal insulation and accessory installations',
      priority: 'medium',
      subtasks: [
        'Apply thermal insulation — foam concrete or expanded clay aggregate 50-75mm (NBC Part 8)',
        'Alternatively use thermocol / XPS sheet insulation below waterproofing layer',
        'Install overhead water tank base with M20 PCC pad per structural provision',
        'Provide structural support for solar panel mounting frames on roof',
        'Install lightning conductor / earthing strip if building > 15m (IS 2309:2000)',
        'Install terrace drain cover plates and access hatch for tank maintenance',
        'Mark and protect any future provision areas on terrace (AC outdoor, antenna)',
      ],
    },
  ],

  'Electrical & Plumbing': [
    // 1. Electrical First Fix — Conduit & Wiring
    {
      title: 'Electrical conduit installation and wiring (first fix)',
      priority: 'high',
      subtasks: [
        'Mark electrical points on walls — switches, sockets, DBs as per approved layout',
        'Cut chases in walls for concealed PVC conduits — max depth 1/3 wall thickness',
        'Run concealed PVC conduits (20mm/25mm) in walls and embed in slab (IS 732:1989)',
        'Install modular switch board boxes and DB boxes at marked locations',
        'Pull copper wiring through conduits — 1.5 sqmm for lighting, 2.5 sqmm for power (IS 694)',
        'Run 4 sqmm cables for AC, geyser and heavy appliance dedicated circuits',
        'Install main switch / RCCB / ELCB at incoming supply point (IS 732)',
        'Install MCBs in distribution board — separate circuits for lighting, power, AC, kitchen',
        'Run separate 6 sqmm cable for water heater / geyser points',
        'Install ceiling fan hooks / fan boxes with proper anchor in slab',
        'Run CCTV, intercom, internet and telephone conduits to designated points',
        'Label all conduits and circuits clearly for future identification',
      ],
    },
    // 2. Earthing & Lightning Protection
    {
      title: 'Earthing system installation and testing',
      priority: 'high',
      subtasks: [
        'Install plate earthing / pipe earthing as per design (IS 3043:2018)',
        'Excavate earth pit — min 1.5m x 1.5m x 3m deep for plate earthing',
        'Place GI/copper earth plate with charcoal and salt layers (IS 3043)',
        'Connect earth lead wire (8 SWG GI) from earth pit to main earth bus bar',
        'Connect all DBs, metal enclosures and exposed metal to earth system',
        'Provide separate earth wire in all power circuits (IS 3043)',
        'Test earth resistance — must be less than 5 ohms, ideally < 2 ohms (IS 3043)',
        'Install lightning protection system if building height > 15m (IS 2309:2000)',
        'Connect lightning arrester to separate earth pit (IS 2309)',
        'Document earth resistance test results with date and instrument details',
      ],
    },
    // 3. Plumbing — Water Supply System
    {
      title: 'Water supply piping and tank installation',
      priority: 'high',
      subtasks: [
        'Install underground water storage sump — size per demand at 135 LPCD (IS 1172:1993)',
        'Install overhead tank (OHT) on structural support — size for 8-12 hours storage',
        'Lay water supply main line from sump to OHT using GI/CPVC pipe (IS 4985 for CPVC)',
        'Install water pump with float valve and auto cut-off in sump and OHT',
        'Run cold water distribution from OHT to all fixtures — CPVC/PPR pipes (IS 15778)',
        'Run hot water CPVC piping from geyser to bathroom and kitchen fixtures',
        'Install isolation valves at each floor, each bathroom and kitchen inlet',
        'Install water meter at incoming main supply line',
        'Provide ball valves in sump and OHT for float-operated filling',
        'Pressure test all water supply lines at 1.5x working pressure — hold 30 min (IS 2065)',
        'Flush all pipes before fixture connection to remove debris',
      ],
    },
    // 4. Plumbing — Drainage & Soil System
    {
      title: 'Drainage, soil and vent pipe installation',
      priority: 'high',
      subtasks: [
        'Install soil pipes (SWR) — 100mm/110mm dia for WC connections (IS 1742:1983)',
        'Install waste pipes — 75mm dia for basin, sink and bath waste water (IS 1742)',
        'Maintain minimum pipe slope 1:40 for waste and 1:20 for soil pipes (IS 1742)',
        'Connect soil pipe to inspection chamber (IC) and then to septic tank or municipal sewer',
        'Install vent pipes — extend above roof level by 300mm minimum for trap seal protection',
        'Install P-trap/S-trap for all floor drains and waste connections (depth min 50mm)',
        'Install anti-siphon traps for upper floor fixtures to prevent back-flow',
        'Provide clean-out plugs at base of each soil stack for maintenance access',
        'Connect kitchen waste through grease trap before joining main drain line',
        'Test drainage system — water test all soil and waste pipes for 15 min (IS 1742)',
        'Install nahani (floor) traps in all bathrooms, kitchen and utility areas',
      ],
    },
    // 5. Bathroom Waterproofing
    {
      title: 'Bathroom and wet area waterproofing',
      priority: 'high',
      subtasks: [
        'Apply waterproofing membrane/coating on bathroom floor slab before screed (IS 3067)',
        'Extend waterproofing up walls — minimum 200mm above FFL, full height in shower area',
        'Seal all pipe penetrations through waterproof membrane watertight',
        'Apply waterproofing on sunken slab portion in all bathrooms',
        'Conduct flood test — fill water to 50mm above FFL for 48 hours — check for leaks',
        'Rectify any leakage and re-test before proceeding to tiling',
        'Apply waterproofing on kitchen sink wall area and utility/wash area floor',
      ],
    },
    // 6. Sanitary Fixture & Fitting Preparation
    {
      title: 'Sanitary fixture rough-in and preparation',
      priority: 'medium',
      subtasks: [
        'Install concealed cistern frames and WC brackets at correct heights',
        'Fix GI / MS bracket for wall-mounted basin at correct height (800mm from FFL)',
        'Install mixing valve rough-in bodies for concealed-type fittings',
        'Fix geyser brackets and provide inlet/outlet stub connections',
        'Install kitchen sink waste coupling and water inlet stub connections',
        'Verify all rough-in positions match architectural fixture layout before tiling',
        'Cap all open pipe ends to prevent blockage during construction',
      ],
    },
    // 7. Rainwater Harvesting & STP
    {
      title: 'Rainwater harvesting system and sewage treatment',
      priority: 'medium',
      subtasks: [
        'Construct/install rainwater harvesting filter chamber near building (NBC Part 9)',
        'Connect rooftop downpipes to rainwater collection system',
        'Install first-flush diverter to divert initial dirty rainwater',
        'Construct recharge well / recharge pit for groundwater recharge (CGWB guidelines)',
        'Alternatively connect filtered rainwater to storage sump for non-potable use',
        'Construct septic tank per IS 2470:1985 if municipal sewer is unavailable',
        'Size septic tank for 24-hour detention — min 1.0 cum per user + 0.3 cum sludge',
        'Construct soak pit / dispersion trench for septic tank effluent (IS 2470)',
        'Install STP (Sewage Treatment Plant) if total discharge > 10 KLD (state norms)',
      ],
    },
  ],

  'Plastering': [
    // 1. Surface Preparation
    {
      title: 'Surface preparation for plastering',
      priority: 'high',
      subtasks: [
        'Hack all concrete surfaces (columns, beams, slab soffits) with chisel marks at 25mm c/c for bonding',
        'Clean all wall surfaces — remove dust, mortar droppings, loose particles',
        'Wet concrete and brick surfaces thoroughly 24 hours before plastering (IS 2402:1963)',
        'Fix chicken wire mesh / GI welded mesh at brick-concrete junctions to prevent cracks (IS 1661)',
        'Fill large voids, honeycombs or gaps with 1:3 cement mortar and allow to set',
        'Apply cement slurry bonding coat on concrete surfaces before plastering (IS 1661:1972)',
        'Install plaster thickness guides (dots and screeds) on walls at 2m grid',
        'Verify all concealed conduits, pipes and chases are covered and flush with wall',
        'Ensure all electrical and plumbing first-fix work is complete before plastering',
      ],
    },
    // 2. Internal Plastering
    {
      title: 'Internal wall and ceiling plastering',
      priority: 'high',
      subtasks: [
        'Apply first coat (base/rough coat) 12mm thick — CM 1:4 for ceiling, CM 1:6 for walls (IS 1661)',
        'Allow first coat to set — minimum 7 days curing before applying finish coat',
        'Apply finish coat 6-8mm thick — CM 1:4 smooth plaster (IS 1661)',
        'Total internal plaster thickness — 12-20mm for walls, 10-15mm for ceiling',
        'Check surface flatness with 3m straight edge — max variation 3mm (IS 2402)',
        'Ensure all corners are true 90-degree angles — check with set square',
        'Form rounded or chamfered edges at external corners for durability',
        'Plaster sill and lintel reveals with proper slope for water drainage',
        'Plaster bathroom walls with waterproof cement plaster — CM 1:3 with waterproofing compound',
        'Cure internal plaster for minimum 7 days by sprinkling water (IS 1661)',
      ],
    },
    // 3. External Plastering
    {
      title: 'External wall plastering and weatherproofing',
      priority: 'high',
      subtasks: [
        'Fix GI chicken mesh at all brick-concrete junctions on external face (IS 1661)',
        'Apply base coat 15-20mm thick — CM 1:4 or CM 1:5 sand-faced plaster (IS 1661)',
        'Apply finish coat — rough cast / pebble dash / sand-faced finish as per design',
        'Provide drip moulds / drip grooves at all chajja (sunshade) edges and projections',
        'Form window sill with outward slope (1:10) and drip groove underneath',
        'Plaster parapet wall both sides with coping on top sloped outward',
        'Apply waterproof plastering on plinth wall up to 300mm above ground level',
        'Ensure all window and door frames are masked/protected during external plastering',
        'Cure external plaster for minimum 14 days — arrange scaffolding for curing access',
        'Inspect for cracks after curing — patch any hairline or shrinkage cracks',
      ],
    },
    // 4. Wall Putty & Surface Finishing
    {
      title: 'Wall putty application and surface finishing',
      priority: 'medium',
      subtasks: [
        'Ensure plaster is fully cured (minimum 21 days) before applying putty',
        'Apply first coat of white cement-based wall putty — 1mm thick (IS 15477:2019)',
        'Sand surface lightly after first coat dries (12-24 hours)',
        'Apply second coat of wall putty — 0.5mm thick for smooth finish',
        'Sand second coat with 400-grit sandpaper for paint-ready smooth surface',
        'Inspect for pin holes, undulations or surface imperfections — rectify with spot putty',
        'Apply putty only on internal surfaces — external walls get direct primer on plaster',
        'Ensure kitchen and bathroom walls marked for tile areas do not get putty (tile adhesive needs rough surface)',
      ],
    },
    // 5. Plastering Quality Checks
    {
      title: 'Plastering quality inspection and testing',
      priority: 'medium',
      subtasks: [
        'Conduct tap test — tap plaster surface with wooden mallet to detect hollow areas',
        'Check plaster thickness at multiple points with pin/depth gauge',
        'Verify surface flatness with 3m straight edge — max 3mm deviation (IS 2402)',
        'Check plumb of plastered walls — max 5mm deviation over 3m height',
        'Verify mortar cube strength for plaster mix — min 3 cubes per floor (IS 2250)',
        'Inspect all corners, reveals, edges for straightness and sharpness',
        'Check all drip moulds and weathering slopes are correctly formed',
        'Document any defective areas requiring rectification before painting',
        'Get engineer/architect sign-off on plastering completion',
      ],
    },
  ],

  'Flooring': [
    // 1. Floor Base Preparation
    {
      title: 'Floor base preparation, leveling and waterproofing',
      priority: 'high',
      subtasks: [
        'Verify floor levels across all rooms using auto-level / laser level instrument',
        'Lay PCC bed / screed over slab — minimum 25-40mm thick with CM 1:2:4 (IS 2571:1970)',
        'Ensure screed surface is level within +/- 3mm over 3m (IS 2571)',
        'Apply waterproof screed in bathrooms, kitchen and utility areas',
        'Form floor slopes in wet areas — 1:40 towards floor drain (IS 1742)',
        'Allow screed to cure for minimum 7 days before tile laying',
        'Mark floor layout lines — reference lines for tile alignment and pattern',
        'Verify all under-floor plumbing and electrical are complete and tested before screeding',
      ],
    },
    // 2. Vitrified/Ceramic Tile Installation — Living Areas
    {
      title: 'Floor tile installation in living areas and bedrooms',
      priority: 'high',
      subtasks: [
        'Procure approved vitrified/ceramic tiles — verify size, shade consistency and quality (IS 15622)',
        'Soak non-vitrified tiles in water for minimum 2 hours before laying',
        'Use tile adhesive or CM 1:3 mortar bed for laying — minimum 10mm bed thickness',
        'Lay tiles with spacers — maintain uniform joint width 2-3mm',
        'Start tile layout from center of room / from entrance for symmetric pattern',
        'Check tile level with spirit level after every 4-5 tiles — ensure flat surface',
        'Cut border tiles with tile cutter — maintain consistent border width',
        'Install skirting tiles (75-100mm height) along all walls — flush with plaster (IS 2571)',
        'Apply tile grout — cement-based or epoxy-based as specified — fill all joints completely',
        'Clean excess grout within 30 minutes — polish surface after 24 hours',
        'Protect newly laid floors with cardboard/tarpaulin during remaining construction',
      ],
    },
    // 3. Bathroom & Kitchen Flooring
    {
      title: 'Bathroom, kitchen and wet area flooring',
      priority: 'high',
      subtasks: [
        'Verify waterproofing membrane is tested and approved before tiling (IS 3067)',
        'Install anti-skid ceramic/vitrified tiles in bathrooms and kitchen (IS 13753)',
        'Maintain floor slope 1:40 towards floor drain / nahani trap in all wet areas',
        'Install dado tiles (wall tiles) up to 2.1m height in bathrooms and 0.6m above kitchen platform',
        'Apply waterproof grout in all bathroom and kitchen tile joints — epoxy grout recommended',
        'Seal tile-to-wall junction and tile-to-drain junction with silicone sealant',
        'Install threshold / door frame transition strip between wet and dry areas',
        'Conduct water flow test — verify water drains completely to floor trap within 5 minutes',
      ],
    },
    // 4. Staircase & Common Area Flooring
    {
      title: 'Staircase, landing and common area flooring',
      priority: 'medium',
      subtasks: [
        'Install staircase tread tiles / granite / kota stone — anti-skid finish mandatory',
        'Provide nosing strip / anti-slip groove on stair tread edge',
        'Install riser tiles — matching or contrasting as per design',
        'Lay landing floor tiles matching staircase or adjacent room pattern',
        'Install skirting on staircase walls — continuous along flight and landing',
        'Lay flooring on entrance porch, lobby and common corridor areas',
        'Install ramp flooring with anti-skid surface for barrier-free access (NBC Cl. 11)',
        'Polish and clean all staircase and common area flooring after installation',
      ],
    },
    // 5. Natural Stone / Marble / Granite Flooring (if applicable)
    {
      title: 'Natural stone, marble or granite flooring installation',
      priority: 'medium',
      subtasks: [
        'Select and approve marble/granite sample — color, vein pattern, thickness (min 18mm)',
        'Test stone for water absorption, flexural strength and density (IS 1124/IS 3622)',
        'Lay stone on CM 1:3 mortar bed — minimum 20mm bed thickness',
        'Maintain uniform joint width 1.5-2mm — fill with matching color grout',
        'Check level and alignment after each slab installation',
        'Apply granite/marble polish — grinding, honing and chemical polishing process',
        'Seal marble/granite surface with stone sealant to prevent staining',
        'Install stone skirting (75-100mm) matching floor stone type',
        'Protect polished stone floors with soft covering during remaining work',
      ],
    },
    // 6. Flooring Quality Inspection
    {
      title: 'Flooring quality inspection and testing',
      priority: 'medium',
      subtasks: [
        'Conduct tap test on all tiles — check for hollow sound indicating poor adhesion',
        'Verify floor level across rooms — max 3mm variation over 3m span',
        'Check joint width uniformity and grout completeness',
        'Verify anti-skid tiles in all wet areas — conduct slip test',
        'Check skirting alignment and height uniformity throughout',
        'Verify floor slopes in bathrooms by water pour test — water reaches drain',
        'Inspect tile edges for chipping or cracking — replace defective tiles',
        'Document completed flooring with photographs and room-wise completion status',
      ],
    },
  ],

  'Finishing': [
    // 1. Painting — Interior
    {
      title: 'Interior painting — primer, putty and emulsion',
      priority: 'high',
      subtasks: [
        'Ensure wall putty is complete, sanded smooth and surface is dust-free',
        'Apply one coat of cement-based primer on all internal walls and ceilings (IS 5411)',
        'Allow primer to dry minimum 6 hours — check for uniform absorption',
        'Apply first coat of interior acrylic emulsion paint — roller/spray application (IS 15489)',
        'Allow first coat to dry 4-6 hours — inspect for coverage uniformity',
        'Apply second coat of interior emulsion — ensure consistent color and sheen',
        'Apply enamel paint on window grills, MS railings and metal surfaces (IS 2932)',
        'Apply wood primer + 2 coats enamel or melamine polish on wooden doors and frames',
        'Apply anti-fungal paint in bathroom ceilings and damp-prone areas',
        'Touch up any scratches, drips or roller marks after final coat dries',
        'Protect painted surfaces from damage during remaining fixture installation',
      ],
    },
    // 2. Painting — Exterior
    {
      title: 'Exterior painting and weather-resistant finishes',
      priority: 'high',
      subtasks: [
        'Apply exterior-grade cement primer on all external plaster surfaces (IS 5411)',
        'Apply first coat of exterior acrylic weather-proof paint (IS 15489)',
        'Apply second coat of exterior paint — consistent color and texture',
        'Paint external MS grills, gates, railings with anti-rust primer + enamel (IS 2932)',
        'Apply texture / designer finish on feature walls if specified',
        'Paint compound wall — both sides with weather-proof exterior paint',
        'Apply waterproof coating on plinth area external wall up to 300mm above GL',
        'Inspect for streaks, patches or uneven coverage — touch up as required',
      ],
    },
    // 3. Door & Window Installation
    {
      title: 'Door and window installation with hardware',
      priority: 'high',
      subtasks: [
        'Install main entrance door — hardwood or engineered wood with frame (IS 1003:2003)',
        'Install internal flush doors with frames — verify standard sizes per drawing (IS 2191)',
        'Install bathroom/WC doors — waterproof WPC or fibre door with ventilation',
        'Install UPVC/aluminum window frames with glass panes — sealed with silicone (IS 1038)',
        'Install mosquito mesh frames on all openable windows and ventilators',
        'Fix all door hardware — mortise locks, handles, tower bolts, door stoppers (IS 3564)',
        'Install door closers on main entrance and bathroom doors',
        'Fix window hardware — latches, stays, handles and safety locks for upper floors',
        'Apply wood polish / laminate finish or enamel paint on all wooden doors',
        'Verify smooth operation of all doors and windows — no sticking or gaps',
        'Install nameplate holder at main entrance',
      ],
    },
    // 4. Electrical & Plumbing Fixture Installation (Final Fix)
    {
      title: 'Electrical and plumbing fixture installation (second fix)',
      priority: 'high',
      subtasks: [
        'Install all modular switch plates, sockets and regulators in switch boards',
        'Install ceiling fans, exhaust fans with proper balancing',
        'Install all light fixtures — tube lights, LED panels, decorative lights as per design',
        'Install geysers / water heaters with safety valve and electrical connection',
        'Install MCBs, RCCB/ELCB in distribution board — label all circuits',
        'Install WC (western closet) with flush tank / concealed cistern connection',
        'Install wash basins with mixer tap, waste coupling and bottle trap',
        'Install bathroom accessories — towel rod, soap dish, mirror, health faucet',
        'Install kitchen sink (SS/granite) with mixer tap and waste coupling',
        'Install washing machine inlet/outlet connections in utility area',
        'Test all electrical points — switches, sockets, fan regulators, light dimmers',
        'Test all plumbing fixtures — flush, taps, drain, hot/cold water flow',
        'Check RCCB/ELCB trip function for safety compliance',
      ],
    },
    // 5. Kitchen Finishing
    {
      title: 'Kitchen platform, chimney and fittings installation',
      priority: 'high',
      subtasks: [
        'Install granite/marble kitchen platform with sink cutout per design',
        'Fix SS kitchen sink with drain board and mixer tap',
        'Install gas pipeline connection stub with isolation valve (IS 5868)',
        'Install chimney / kitchen exhaust hood with ducting to exterior',
        'Install kitchen wall cabinet and base cabinet as per modular kitchen design',
        'Install electrical points for chimney, water purifier, microwave, mixer grinder',
        'Provide under-cabinet lighting if specified in design',
        'Test water flow, gas connection safety and electrical functionality',
      ],
    },
    // 6. MS Grills, Railings & Safety Features
    {
      title: 'MS grills, railings, safety grills and metalwork',
      priority: 'high',
      subtasks: [
        'Install MS/SS staircase railing — minimum height 900mm with vertical balusters (NBC Cl. 8.7.5)',
        'Ensure railing baluster spacing max 100mm to prevent child entrapment (NBC)',
        'Install MS safety grills on all windows — especially upper floors (IS 1038)',
        'Install balcony railing — minimum 1050mm height with toe guard (NBC Cl. 8.8)',
        'Install terrace safety railing if parapet height < 1.2m',
        'Install main gate — MS/wrought iron with locking mechanism',
        'Apply anti-rust primer + 2 coats enamel paint on all MS fabrication (IS 2932)',
        'Verify all grills and railings for structural adequacy and weld quality',
      ],
    },
    // 7. External Works — Compound Wall, Driveway, Landscaping
    {
      title: 'External works — compound wall, paving and landscaping',
      priority: 'medium',
      subtasks: [
        'Construct compound wall — brick/block with RCC columns at 3m c/c',
        'Apply plaster and paint on compound wall — both faces',
        'Install main gate pillars with structural foundation',
        'Install main gate (MS/wrought iron) with locking, stopper and auto-close if specified',
        'Lay paver blocks / concrete flooring for driveway and car parking area',
        'Construct open drain / storm water channel along compound periphery',
        'Lay garden area with topsoil, plant saplings and lawn grass as per landscape design',
        'Install external lighting — porch light, garden lights, compound wall lights',
        'Install name plate and house number on gate pillar or building facade',
        'Construct servant quarter / watchman room if specified in design',
      ],
    },
    // 8. Final Electrical Testing & Certification
    {
      title: 'Final electrical testing, metering and certification',
      priority: 'high',
      subtasks: [
        'Conduct insulation resistance (IR) test on all circuits — min 1 Megohm (IS 732)',
        'Test earth continuity on all power sockets and exposed metal parts',
        'Verify earth resistance < 5 ohms at earth pit (IS 3043)',
        'Test RCCB/ELCB tripping at 30mA leakage current — must trip within 200ms',
        'Verify phase-neutral-earth wiring correctness on all sockets with socket tester',
        'Test all light and fan circuits under load for voltage drop < 5% (IS 732)',
        'Get permanent electrical supply meter installed from electricity board',
        'Obtain electrical installation test certificate from licensed electrical contractor (IS 732)',
      ],
    },
  ],

  'Handover': [
    // 1. Pre-Handover Inspection & Punch List
    {
      title: 'Pre-handover inspection and punch list preparation',
      priority: 'high',
      subtasks: [
        'Conduct room-by-room inspection — walls, ceiling, flooring, fixtures, fittings',
        'Check all doors and windows — smooth operation, locking, glass, sealant, mosquito mesh',
        'Inspect all electrical points — switches, sockets, fans, lights, regulators working',
        'Test all plumbing fixtures — flush, taps (hot+cold), basin, sink, drains, no leaks',
        'Inspect painting quality — no patches, drips, roller marks, color uniformity',
        'Check tile quality — no hollow tiles, chipped edges, grout completeness',
        'Verify flooring level and slope in bathrooms — water drains to trap',
        'Inspect external — compound wall, gate, driveway, drainage, landscaping',
        'Inspect terrace — waterproofing, parapet, tank, drainage, no ponding',
        'Prepare detailed snag/punch list with location, defect description and photograph',
        'Assign responsibility and deadline for each punch list item to contractor',
      ],
    },
    // 2. Punch List Rectification
    {
      title: 'Punch list rectification and re-inspection',
      priority: 'high',
      subtasks: [
        'Contractor rectifies all identified snags/defects per punch list',
        'Re-inspect each rectified item — verify defect is fully resolved',
        'Conduct second round inspection if new defects found during rectification',
        'Get owner/PM sign-off on punch list completion before handover',
        'Touch up painting, cleaning and polishing after rectification work',
        'Ensure site is cleaned — remove all construction debris, materials and temporary structures',
      ],
    },
    // 3. MEP Testing & Commissioning
    {
      title: 'MEP system testing, commissioning and performance verification',
      priority: 'high',
      subtasks: [
        'Final test all electrical circuits — IR test, earth test, load test (IS 732)',
        'Test RCCB/ELCB trip function on all distribution boards',
        'Test water pump operation — auto on/off with float switch in sump and OHT',
        'Run all taps simultaneously — verify water pressure and flow adequacy',
        'Flush all drainage lines — verify free flow without blockage',
        'Test hot water system — geyser heats within rated time, no leaks',
        'Test rainwater harvesting system — flush diverter and filter operation',
        'Verify septic tank / STP is functioning per design capacity (IS 2470)',
        'Test overhead tank overflow pipe is connected to proper discharge point',
        'Commission any installed home automation, intercom or CCTV systems',
      ],
    },
    // 4. Documentation, Certificates & As-Built Drawings
    {
      title: 'Documentation compilation, certificates and as-built drawings',
      priority: 'high',
      subtasks: [
        'Compile all concrete cube test reports with 7-day and 28-day strength results',
        'Compile all material test certificates — cement, steel, bricks, aggregate, sand',
        'Collect anti-termite treatment certificate with warranty period',
        'Collect waterproofing treatment certificate and warranty',
        'Collect electrical installation test certificate from licensed contractor (IS 732)',
        'Obtain earth resistance test report (IS 3043)',
        'Prepare as-built architectural drawings reflecting actual construction',
        'Prepare as-built structural drawings with any field modifications',
        'Prepare as-built MEP drawings — electrical layout, plumbing layout',
        'Compile all vendor warranties — paint, plumbing fittings, electrical, doors, tiles',
        'Prepare maintenance schedule — painting cycle, tank cleaning, termite re-treatment',
      ],
    },
    // 5. Statutory Completion & Occupancy Certificate
    {
      title: 'Statutory completion and occupancy certificate',
      priority: 'high',
      subtasks: [
        'Apply for completion certificate from local authority',
        'Submit as-built drawings and photographs to local body',
        'Obtain structural stability certificate for completed building from licensed engineer',
        'Obtain fire safety compliance certificate from fire department (NBC Part 4)',
        'Obtain occupancy certificate (OC) from local municipal authority',
        'Get permanent water supply connection transferred to owner name',
        'Get permanent electrical meter connection activated and transferred to owner',
        'Apply for property tax assessment and pay applicable charges',
        'Register the completed building/property if required (state-specific)',
      ],
    },
    // 6. Formal Handover to Owner
    {
      title: 'Formal handover, key delivery and project closure',
      priority: 'high',
      subtasks: [
        'Conduct final walkthrough with owner — room by room demonstration',
        'Demonstrate operation of all systems — electrical, plumbing, pump, geyser, intercom',
        'Hand over all keys — main door, rooms, gate, electrical panel, tank access',
        'Hand over sanctioned plan, completion certificate, OC and all statutory documents',
        'Hand over all test certificates, warranty cards and maintenance manuals',
        'Hand over as-built drawings (architectural, structural, MEP) in hard and soft copy',
        'Hand over spare tiles, paint (touch-up quantity) and extra hardware',
        'Define defect liability period terms — typically 12 months from handover',
        'Release final payment to contractor after retention period (per contract)',
        'Close site office, remove temporary structures and restore site access',
        'Record project completion date and file project closure report',
      ],
    },
  ],
};

export default DEFAULT_STAGE_TASKS;
