export const NAV_CONFIG = {
  owner: [
    { label: 'Dashboard', path: '/dashboard', icon: 'grid' },
    { label: 'Projects', path: '/projects', icon: 'briefcase' },
    { label: 'Team', path: '/team', icon: 'users' },
    { label: 'Stages', path: '/stages', icon: 'layers' },
    { label: 'Tasks', path: '/tasks', icon: 'check-square' },
    { label: 'Materials', path: '/materials', icon: 'package' },
    { label: 'Vendors', path: '/vendors', icon: 'truck' },
    { label: 'Inventory', path: '/inventory', icon: 'box' },
    { label: 'Budget', path: '/budget', icon: 'dollar' },
    { label: 'Expenses', path: '/expenses', icon: 'credit-card' },
    { label: 'Payments', path: '/payments', icon: 'dollar' },
    { label: 'Quality', path: '/quality', icon: 'shield' },
    { label: 'NCRs', path: '/ncrs', icon: 'alert-octagon' },
    { label: 'RFIs', path: '/rfis', icon: 'help-circle' },
    { label: 'Change Orders', path: '/change-orders', icon: 'repeat' },
    { label: 'Safety', path: '/safety', icon: 'hard-hat' },
    { label: 'RA Bills', path: '/ra-bills', icon: 'file-text' },
    { label: 'Documents', path: '/documents', icon: 'folder' },
    { label: 'Submittals', path: '/submittals', icon: 'clipboard' },
    { label: 'Meetings', path: '/meetings', icon: 'calendar' },
    { label: 'Daily Logs', path: '/daily-logs', icon: 'clipboard' },
    { label: 'Workflows', path: '/workflows', icon: 'git-branch' },
    { label: 'Audit Log', path: '/audit-log', icon: 'file-text' },
    { label: 'Reports', path: '/reports', icon: 'bar-chart' },
    { label: 'Estimator', path: '/estimator', icon: 'calculator' },
  ],
  pm: [
    { label: 'Dashboard', path: '/dashboard', icon: 'grid' },
    { label: 'Stages', path: '/stages', icon: 'layers' },
    { label: 'Tasks', path: '/tasks', icon: 'check-square' },
    { label: 'Materials', path: '/materials', icon: 'package' },
    { label: 'Quality', path: '/quality', icon: 'shield' },
    { label: 'NCRs', path: '/ncrs', icon: 'alert-octagon' },
    { label: 'RFIs', path: '/rfis', icon: 'help-circle' },
    { label: 'Change Orders', path: '/change-orders', icon: 'repeat' },
    { label: 'Safety', path: '/safety', icon: 'hard-hat' },
    { label: 'RA Bills', path: '/ra-bills', icon: 'file-text' },
    { label: 'Documents', path: '/documents', icon: 'folder' },
    { label: 'Submittals', path: '/submittals', icon: 'clipboard' },
    { label: 'Meetings', path: '/meetings', icon: 'calendar' },
    { label: 'Daily Logs', path: '/daily-logs', icon: 'clipboard' },
    { label: 'Workflows', path: '/workflows', icon: 'git-branch' },
    { label: 'Audit Log', path: '/audit-log', icon: 'file-text' },
    { label: 'Reports', path: '/reports', icon: 'bar-chart' },
    { label: 'Estimator', path: '/estimator', icon: 'calculator' },
  ],
  engineer: [
    { label: 'Dashboard', path: '/dashboard', icon: 'grid' },
    { label: 'Stages', path: '/stages', icon: 'layers' },
    { label: 'Tasks', path: '/tasks', icon: 'check-square' },
    { label: 'Daily Logs', path: '/daily-logs', icon: 'clipboard' },
    { label: 'Materials', path: '/materials', icon: 'package' },
    { label: 'Quality', path: '/quality', icon: 'shield' },
    { label: 'NCRs', path: '/ncrs', icon: 'alert-octagon' },
    { label: 'RFIs', path: '/rfis', icon: 'help-circle' },
    { label: 'Change Orders', path: '/change-orders', icon: 'repeat' },
    { label: 'Safety', path: '/safety', icon: 'hard-hat' },
    { label: 'Documents', path: '/documents', icon: 'folder' },
    { label: 'Submittals', path: '/submittals', icon: 'clipboard' },
    { label: 'Meetings', path: '/meetings', icon: 'calendar' },
    { label: 'Workflows', path: '/workflows', icon: 'git-branch' },
    { label: 'Estimator', path: '/estimator', icon: 'calculator' },
  ],
  contractor: [
    { label: 'Dashboard', path: '/dashboard', icon: 'grid' },
    { label: 'Stages', path: '/stages', icon: 'layers' },
    { label: 'Materials', path: '/materials', icon: 'package' },
    { label: 'Vendors', path: '/vendors', icon: 'truck' },
    { label: 'Inventory', path: '/inventory', icon: 'box' },
    { label: 'Labor', path: '/daily-logs', icon: 'users' },
    { label: 'Tasks', path: '/tasks', icon: 'check-square' },
    { label: 'RFIs', path: '/rfis', icon: 'help-circle' },
    { label: 'Safety', path: '/safety', icon: 'hard-hat' },
    { label: 'RA Bills', path: '/ra-bills', icon: 'file-text' },
    { label: 'Purchase Orders', path: '/payments', icon: 'file' },
    { label: 'Documents', path: '/documents', icon: 'folder' },
    { label: 'Submittals', path: '/submittals', icon: 'clipboard' },
    { label: 'Meetings', path: '/meetings', icon: 'calendar' },
    { label: 'Workflows', path: '/workflows', icon: 'git-branch' },
    { label: 'Estimator', path: '/estimator', icon: 'calculator' },
  ],
  procurement: [
    { label: 'Dashboard', path: '/dashboard', icon: 'grid' },
    { label: 'Materials', path: '/materials', icon: 'package' },
    { label: 'Vendors', path: '/vendors', icon: 'truck' },
    { label: 'Inventory', path: '/inventory', icon: 'box' },
    { label: 'Purchase Orders', path: '/payments', icon: 'file' },
    { label: 'Documents', path: '/documents', icon: 'folder' },
    { label: 'Workflows', path: '/workflows', icon: 'git-branch' },
    { label: 'Estimator', path: '/estimator', icon: 'calculator' },
  ],
  accounts: [
    { label: 'Dashboard', path: '/dashboard', icon: 'grid' },
    { label: 'Expenses', path: '/expenses', icon: 'credit-card' },
    { label: 'Payments', path: '/payments', icon: 'dollar' },
    { label: 'Budget', path: '/budget', icon: 'trending-up' },
    { label: 'RA Bills', path: '/ra-bills', icon: 'file-text' },
    { label: 'Workflows', path: '/workflows', icon: 'git-branch' },
    { label: 'Estimator', path: '/estimator', icon: 'calculator' },
  ],
  inspector: [
    { label: 'Dashboard', path: '/dashboard', icon: 'grid' },
    { label: 'Inspections', path: '/quality', icon: 'shield' },
    { label: 'NCRs', path: '/ncrs', icon: 'alert-octagon' },
    { label: 'Defects', path: '/defects', icon: 'alert-triangle' },
    { label: 'Safety', path: '/safety', icon: 'hard-hat' },
    { label: 'Stages', path: '/stages', icon: 'layers' },
    { label: 'Documents', path: '/documents', icon: 'folder' },
    { label: 'Submittals', path: '/submittals', icon: 'clipboard' },
    { label: 'Workflows', path: '/workflows', icon: 'git-branch' },
    { label: 'Checklists', path: '/stages', icon: 'check-square' },
  ],
};

export const ROLE_LABELS = {
  owner: 'Owner',
  pm: 'Project Manager',
  engineer: 'Site Engineer',
  contractor: 'Contractor',
  procurement: 'Procurement Officer',
  accounts: 'Accounts Manager',
  inspector: 'Quality Inspector',
};
